/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusRouteImport } from './routes/status'
import { Route as ReleasesRouteImport } from './routes/releases'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemonstracaoRouteImport } from './routes/demonstracao'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemonstracaoIndexRouteImport } from './routes/demonstracao.index'
import { Route as LoginDiagRouteImport } from './routes/login.diag'
import { Route as DemonstracaoPacienteRouteImport } from './routes/demonstracao.paciente'
import { Route as DemonstracaoClinicaRouteImport } from './routes/demonstracao.clinica'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'

const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesRoute = ReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemonstracaoRoute = DemonstracaoRouteImport.update({
  id: '/demonstracao',
  path: '/demonstracao',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemonstracaoIndexRoute = DemonstracaoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemonstracaoRoute,
} as any)
const LoginDiagRoute = LoginDiagRouteImport.update({
  id: '/diag',
  path: '/diag',
  getParentRoute: () => LoginRoute,
} as any)
const DemonstracaoPacienteRoute = DemonstracaoPacienteRouteImport.update({
  id: '/paciente',
  path: '/paciente',
  getParentRoute: () => DemonstracaoRoute,
} as any)
const DemonstracaoClinicaRoute = DemonstracaoClinicaRouteImport.update({
  id: '/clinica',
  path: '/clinica',
  getParentRoute: () => DemonstracaoRoute,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/demonstracao': typeof DemonstracaoRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/releases': typeof ReleasesRoute
  '/status': typeof StatusRoute
  '/demonstracao/clinica': typeof DemonstracaoClinicaRoute
  '/demonstracao/paciente': typeof DemonstracaoPacienteRoute
  '/login/diag': typeof LoginDiagRoute
  '/demonstracao/': typeof DemonstracaoIndexRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRouteWithChildren
  '/releases': typeof ReleasesRoute
  '/status': typeof StatusRoute
  '/demonstracao/clinica': typeof DemonstracaoClinicaRoute
  '/demonstracao/paciente': typeof DemonstracaoPacienteRoute
  '/login/diag': typeof LoginDiagRoute
  '/demonstracao': typeof DemonstracaoIndexRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/demonstracao': typeof DemonstracaoRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/releases': typeof ReleasesRoute
  '/status': typeof StatusRoute
  '/demonstracao/clinica': typeof DemonstracaoClinicaRoute
  '/demonstracao/paciente': typeof DemonstracaoPacienteRoute
  '/login/diag': typeof LoginDiagRoute
  '/demonstracao/': typeof DemonstracaoIndexRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/demonstracao'
    | '/login'
    | '/releases'
    | '/status'
    | '/demonstracao/clinica'
    | '/demonstracao/paciente'
    | '/login/diag'
    | '/demonstracao/'
    | '/api/public/health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/releases'
    | '/status'
    | '/demonstracao/clinica'
    | '/demonstracao/paciente'
    | '/login/diag'
    | '/demonstracao'
    | '/api/public/health'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/demonstracao'
    | '/login'
    | '/releases'
    | '/status'
    | '/demonstracao/clinica'
    | '/demonstracao/paciente'
    | '/login/diag'
    | '/demonstracao/'
    | '/api/public/health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DemonstracaoRoute: typeof DemonstracaoRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
  ReleasesRoute: typeof ReleasesRoute
  StatusRoute: typeof StatusRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases': {
      id: '/releases'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof ReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demonstracao': {
      id: '/demonstracao'
      path: '/demonstracao'
      fullPath: '/demonstracao'
      preLoaderRoute: typeof DemonstracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demonstracao/': {
      id: '/demonstracao/'
      path: '/'
      fullPath: '/demonstracao/'
      preLoaderRoute: typeof DemonstracaoIndexRouteImport
      parentRoute: typeof DemonstracaoRoute
    }
    '/login/diag': {
      id: '/login/diag'
      path: '/diag'
      fullPath: '/login/diag'
      preLoaderRoute: typeof LoginDiagRouteImport
      parentRoute: typeof LoginRoute
    }
    '/demonstracao/paciente': {
      id: '/demonstracao/paciente'
      path: '/paciente'
      fullPath: '/demonstracao/paciente'
      preLoaderRoute: typeof DemonstracaoPacienteRouteImport
      parentRoute: typeof DemonstracaoRoute
    }
    '/demonstracao/clinica': {
      id: '/demonstracao/clinica'
      path: '/clinica'
      fullPath: '/demonstracao/clinica'
      preLoaderRoute: typeof DemonstracaoClinicaRouteImport
      parentRoute: typeof DemonstracaoRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DemonstracaoRouteChildren {
  DemonstracaoClinicaRoute: typeof DemonstracaoClinicaRoute
  DemonstracaoPacienteRoute: typeof DemonstracaoPacienteRoute
  DemonstracaoIndexRoute: typeof DemonstracaoIndexRoute
}

const DemonstracaoRouteChildren: DemonstracaoRouteChildren = {
  DemonstracaoClinicaRoute: DemonstracaoClinicaRoute,
  DemonstracaoPacienteRoute: DemonstracaoPacienteRoute,
  DemonstracaoIndexRoute: DemonstracaoIndexRoute,
}

const DemonstracaoRouteWithChildren = DemonstracaoRoute._addFileChildren(
  DemonstracaoRouteChildren,
)

interface LoginRouteChildren {
  LoginDiagRoute: typeof LoginDiagRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginDiagRoute: LoginDiagRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DemonstracaoRoute: DemonstracaoRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
  ReleasesRoute: ReleasesRoute,
  StatusRoute: StatusRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
